### ISSUE TITLE
Timing issue on topicToQueueMapping example

### ISSUE THREAD

**Issue by wari** [SolaceSamples/solace-samples-java#5]
Hit this particular exception when running on a VMR. Temporary queue still exists, and the last message (Message number 5) is still in the queue.

```
wari@box:~/src/solace-samples-java$ ./build/staged/bin/topicToQueueMapping 192.168.29.133
TopicToQueueMapping initializing...
Sep 16, 2016 10:58:39 AM com.solacesystems.jcsmp.protocol.impl.TcpClientChannel call
INFO: Connecting to host 'orig=192.168.29.133, host=192.168.29.133' (host 1 of 1, smfclient 2, attempt 1 of 1, this_host_attempt: 1 of 1)
Sep 16, 2016 10:58:39 AM com.solacesystems.jcsmp.protocol.impl.TcpClientChannel call
INFO: Connected to host 'orig=192.168.29.133, host=192.168.29.133' (smfclient 2)
All required capabilities supported!
Provision queue 'Q/tutorial/topicToQueueMapping' on the appliance...Producer received response for msg ID #2
Producer received response for msg ID #4
Producer received response for msg ID #6
Producer received response for msg ID #8
Sent messages.
Producer received response for msg ID #10
TextMessage received: 'Message number 1'
Message Dump:
Destination:                            Topic 'T/mapped/topic/sample'
Class Of Service:                       USER_COS_1
DeliveryMode:                           PERSISTENT
Message Id:                             17670
Binary Attachment:                      len=19
  1c 13 4d 65 73 73 61 67    65 20 6e 75 6d 62 65 72    ..Message.number
  20 31 00                                              .1.

.... CUT ...

TextMessage received: 'Message number 5'
Message Dump:
Destination:                            Topic 'T/mapped/topic/sample'
Class Of Service:                       USER_COS_1
DeliveryMode:                           PERSISTENT
Message Id:                             17674
Binary Attachment:                      len=19
  1c 13 4d 65 73 73 61 67    65 20 6e 75 6d 62 65 72    ..Message.number
  20 35 00                                              .5.


Sep 16, 2016 10:58:40 AM com.solacesystems.jcsmp.impl.JCSMPXMLMessage ackMessage
WARNING: ackMessage is ignored because the message acknowledgement mode is auto-ack
Finished consuming expected messages.
Sep 16, 2016 10:58:40 AM com.solacesystems.jcsmp.impl.flow.FlowHandleImpl triggerAsyncDelivery
WARNING: Exception occurred in async delivery for flow 18
java.lang.IllegalStateException: Attempted an operation on a closed message consumer.
        at com.solacesystems.jcsmp.impl.flow.FlowHandleImpl.ackMessage(FlowHandleImpl.java:1766)
        at com.solacesystems.jcsmp.impl.flow.FlowHandleImpl.triggerAsyncDelivery(FlowHandleImpl.java:1449)
        at com.solacesystems.jcsmp.protocol.nio.impl.ConsumerMessageNotification.handleNotification(ConsumerMessageNotification.java:22)
        at com.solacesystems.jcsmp.protocol.nio.impl.ConsumerNotificationDispatcher.eventLoop(ConsumerNotificationDispatcher.java:112)
        at com.solacesystems.jcsmp.protocol.nio.impl.ConsumerNotificationDispatcher.run(ConsumerNotificationDispatcher.java:130)
        at java.lang.Thread.run(Thread.java:745)

Sep 16, 2016 10:58:40 AM com.solacesystems.jcsmp.impl.RequestResponseTask startTimer
INFO: RequestResponseTask: skipped startTimer(), timeout:10000 startTimerFlag:false
Exiting.
Sep 16, 2016 10:58:40 AM com.solacesystems.jcsmp.protocol.impl.TcpClientChannel close
INFO: Channel Closed (smfclient 2)
Consumer received exception: com.solacesystems.jcsmp.JCSMPException: Error calling XMLMessagelistener
```

**Comment by Mrc0113** [comment]
Closing stale issue due to inactivity. :sleeping:
To have this issue re-opened please add a comment below with a detailed explanation.  
Thank you for your contributions :heart:
